- name: Install Ethereum Depdendencies
  tags: litecoin_dependencies
  become: true
  package: name={{ item }} state=latest
  with_items:
    - golang

- name: Clone Ethereum
  tags: clone_ethereum
  git:
    repo: https://github.com/ethereum/go-ethereum.git
    dest: "{{ userpath }}/Dev/go-ethereum"
    version: "{{ ethereum_version }}"

- name: Autogen Command {{ currency_type }}
  tags: autogen
  command: sh autogen.sh
  args:
    chdir: "{{ userpath }}/Dev/{{ currency_type }}" 

- name: Configure Command {{ currency_type }}
  tags: configure
  command: sh configure --disable-wallet
  args: 
    chdir: "{{ userpath }}/Dev/{{ currency_type }}"

- name: Make Command {{ currency_type }}
  tags: make
  command: make -j2
  args:
    chdir: "{{ userpath }}/Dev/{{ currency_type }}" 

- name: Install {{ currency_type }}
  tags: install
  become: true
  command: make install
  args:
    chdir: "{{ userpath }}/Dev/{{ currency_type }}" 
