- name: Install Ethereum Depdendencies
  tags: litecoin_dependencies
  become: true
  package: name={{ item }} state=latest
  with_items:
    - golang
    - build-essential

- name: Clone Ethereum
  tags: clone_ethereum
  git:
    repo: https://github.com/ethereum/go-ethereum.git
    dest: "{{ userpath }}/Dev/go-ethereum"
    version: "{{ ethereum_version }}"

- name: Make Command {{ currency_type }}
  tags: make
  command: make geth
  args:
    chdir: "{{ userpath }}/Dev/go-ethereum"

- name: Install {{ currency_type }}
  tags: install
  become: true
  command: cp {{ userpath }}/Dev/go-ethereum/build/bin/geth /usr/local/bin
  args:
    chdir: "{{ userpath }}/Dev/go-ethereum"
