bitcoin_version: v0.15.1

monitrc_file_content: |
  check process {{ currency_type }}d with pidfile "{{ blockchainpath }}/{{ currency_type }}.pid"
      start program "/usr/local/bin/{{ currency_type }}d -datadir={{ blockchainpath }} -daemon"
      stop program "/usr/local/bin/{{ currency_type }}-cli -datadir={{ blockchainpath }} stop"
