---
- hosts: all

  vars_files:
    - vars/general.yml
    - vars/releases.yml

  tasks:
    - name: Create Dev Dir
      tags: setup_dir
      file: dest={{ userpath }}/{{ item }} state=directory owner={{ username }} recurse=yes
      with_items :
        - Dev

    - name: Automount External Storage
      tags: usb_automount
      become: true
      lineinfile:
        dest: /etc/fstab
        state: present
        regexp: '^/dev/sda1 {{ blockchainpath }}  vfat  uid=pi,gid=pi,umask=0022,sync,auto,nosuid,rw,nouser 0 0'
        line: '/dev/sda1 {{ blockchainpath }}  vfat  uid=pi,gid=pi,umask=0022,sync,auto,nosuid,rw,nouser 0 0'

    - name: Enlarge Swap File
      tags: enlarge_swap
      become: true
      lineinfile:
        dest: /etc/dphys-swapfile
        state: present
        regexp: '^CONF_SWAPSIZE='
        line: 'CONF_SWAPSIZE=1000'

    #TODO:User a handler for reboot or post_task
    - name: Enable Swapon
      tags: enable_swapon
      shell: |
        dphys-swapfile setup
        dphys-swapfile swapon

    - name: Update & Upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day   
   
    - name: Install Basic Depdendency Packages
      tags: dependencies
      become: true
      package: name={{ item }} state=latest
      with_items:
        - tmux
        - monit

    - include_role:
        name: bitcoin
        when: "{{ currency_type }} == 'bitcoin'"

    - include_role:
        name: litecoin
        when: "{{ currency_type }} == 'litecoin'"

    - include_role:
        name: ethereum
        when: "{{ currency_type }} == 'ethereum'"

    - name: Autogen Command {{ currency_type }}
      tags: autogen
      command: sh autogen.sh
      args:
        chdir: "{{ userpath }}/Dev/{{ currency_type }}" 

    - name: Configure Command {{ currency_type }}
      tags: configure
      command: sh configure --disable-wallet
      args: 
        chdir: "{{ userpath }}/Dev/{{ currency_type }}"

    - name: Make Command {{ currency_type }}
      tags: make
      command: make -j2
      args:
        chdir: "{{ userpath }}/Dev/{{ currency_type }}" 

    - name: Install {{ currency_type }}
      tags: install
      become: true
      command: make install
      args:
        chdir: "{{ userpath }}/Dev/{{ currency_type }}" 

#TODO: probably can't just run daemon, we need to restart.

    - name: Run Litecoin Daemon
      tags: run daemon
      command: litecoind -datadir={{ blockchainpath }} -daemon
      args:
        chdir: "{{ userpath }}"
