---
- hosts: all

  vars_files:
    - vars/general.yml
    - vars/releases.yml

  tasks:
    - name: Create Dev Dir
      tags: setup_dir
      file: dest={{ userpath }}/{{ item }} state=directory owner={{ username }} recurse=yes
      with_items :
        - Dev

#TODO: tell where to mount rasppi location

    - name: Enlarge Swap File
      tags: enlarge_swap
      become: true
      lineinfile:
        dest: /etc/dphys-swapfile
        state: present
        regexp: '^CONF_SWAPSIZE='
        line: 'CONF_SWAPSIZE=1000'

    - name: Enable Swapon
      tags: enable_swapon
      shell: |
        dphys-swapfile setup
        dphys-swapfile swapon

    - name: Update & Upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day   
   
    - name: Install Basic Depdendency Packages
      tags: dependencies
      become: true
      package: name={{ item }} state=latest
      with_items:
        - tmux
        - monit

    - name: Install Litecoin Depdendencies
      tags: litecoin_dependencies
      become: true
      package: name={{ item }} state=latest
      with_items:
        - autoconf 
        - libtool   
        - libssl-dev 
        - libboost-all-dev 
        - libminiupnpc-dev 

    - name: Install Ethereum Depdendencies
      tags: litecoin_dependencies
      become: true
      package: name={{ item }} state=latest
      with_items:
        - golang
      when: currency_type == "ethereum"

#TODO: let's make roles for these so that we can separate out

    - name: Clone Bitcoin
      tags: clone_bitcoin
      git:
        repo: https://github.com/bitcoin/bitcoin.git 
        dest: "{{ userpath }}/Dev/bitcoin"
        update: no
      when: currency_type == "bitcoin"

    - name: Clone Litecoin
      tags: clone_litecoin
      git:
        repo: https://github.com/litecoin-project/litecoin.git 
        dest: "{{ userpath }}/Dev/litecoin"
        version: "{{ litecoin_version }}"
      when: currency_type == "litecoin"

    - name: Clone Ethereum
      tags: clone_ethereum
      git:
        repo: https://github.com/ethereum/go-ethereum.git
        dest: "{{ userpath }}/Dev/go-ethereum"
        update: no
      when: currency_type == "ethereum"

    - name: Autogen Command {{ currency_type }}
      tags: autogen
      command: sh autogen.sh
      args:
        chdir: "{{ userpath }}/Dev/{{ currency_type }}" 
      when: currency_type == "litecoin"

    - name: Configure Command {{ currency_type }}
      tags: configure
      command: sh configure --disable-wallet
      args: 
        chdir: "{{ userpath }}/Dev/{{ currency_type }}"

    - name: Make Command {{ currency_type }}
      tags: make
      command: make -j2
      args:
        chdir: "{{ userpath }}/Dev/{{ currency_type }}" 

    - name: Install {{ currency_type }}
      tags: install
      become: true
      command: make install
      args:
        chdir: "{{ userpath }}/Dev/{{ currency_type }}" 

#TODO: probably can't just run daemon, we need to restart.

    - name: Run Litecoin Daemon
      tags: run daemon
      command: litecoind -datadir={{ blockchainpath }} -daemon
      args:
        chdir: "{{ userpath }}"
