---
- hosts: all

  vars_files:
    - vars/general.yml

  tasks:
    - name: Create Dev Dir
      tags: setup_dir
      file: dest={{ userpath }}/{{ item }} state=directory owner={{ username }} recurse=yes
      with_items :
        - Dev

    - name: Enlarge Swap File
      tags: enlarge_swap
      become: true
      lineinfile:
        dest: /etc/dphys-swapfile
        state: present
        regexp: '^CONF_SWAPSIZE='
        line: 'CONF_SWAPSIZE=1000'

    - name: Enable Swapon
      tags: enable_swapon
      shell: |
        dphys-swapfile setup
        dphys-swapfile swapon

    - name: Update & Upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day   
   
    - name: Install Basic Depdendency Packages
      tags: dependencies
      become: true
      package: name={{ item }} state=latest
      with_items:
        - tmux
        - monit

    - name: Install Litecoin Depdendencies
      tags: litecoin_dependencies
      become: true
      package: name={{ item }} state=latest
      with_items:
        - autoconf 
        - libtool   
        - libssl-dev 
        - libboost-all-dev 
        - libminiupnpc-dev 

    - name: Install Ethereum Depdendencies
      tags: litecoin_dependencies
      become: true
      package: name={{ item }} state=latest
      with_items:
        - golang
      when: type == "ethereum"

    - name: Clone Bitcoin
      tags: clone_bitcoin
      git:
        repo: https://github.com/bitcoin/bitcoin.git 
        dest: "{{ userpath }}/Dev/bitcoin"
      when: type == "bitcoin"

    - name: Clone Litecoin
      tags: clone_litecoin
      git:
        repo: https://github.com/litecoin-project/litecoin.git 
        dest: "{{ userpath }}/Dev/litecoin"
        force: yes
      when: type == "litecoin"

    - name: Clone Ethereum
      tags: clone_ethereum
      git:
        repo: https://github.com/ethereum/go-ethereum.git
        dest: "{{ userpath }}/Dev/go-ethereum"
      when: type == "ethereum"

    - name: Autogen Litecoin
      tags: autogen_litecoin
      command: sh autogen.sh
      args:
        chdir: "{{ userpath }}/Dev/litecoin" 
















