---
- hosts: all

  vars_files:
    - vars/general.yml

  pre_tasks:
    - name: Create Dev Dir
      tags: setup_dir
      file: dest={{ userpath }}/{{ item }} state=directory owner={{ username }} recurse=yes
      with_items :
        - Dev

    #This option is available in raspi-config
    - name: Memory Split
      tags: memory_split
      become: true
      lineinfile:
        dest: /boot/config.txt
        state: present
        regexp: '^gpu_mem='
        line: 'gpu_mem=16'

    - name: Automount External Storage
      tags: usb_automount
      become: true
      lineinfile:
        dest: /etc/fstab
        state: present
        regexp: '^/dev/sda1 {{ blockchainpath }}  vfat  uid=pi,gid=pi,umask=0022,sync,auto,nosuid,rw,nouser 0 0'
        line: '/dev/sda1 {{ blockchainpath }}  vfat  uid=pi,gid=pi,umask=0022,sync,auto,nosuid,rw,nouser 0 0'

    - name: Enlarge Swap File
      tags: enlarge_swap
      become: true
      lineinfile:
        dest: /etc/dphys-swapfile
        state: present
        regexp: '^CONF_SWAPSIZE='
        line: 'CONF_SWAPSIZE=1000'

    - name: Enable Swapon
      tags: enable_swapon
      shell: |
        dphys-swapfile setup
        dphys-swapfile swapon

    - name: Update & Upgrade apt packages
      tags: update_upgrade
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: "{{ apt_get_valid_time }}"

    #note monit auto inits on install under /usr/bin/monit -c /etc/monit/monitrc process   
    - name: Install Basic Depdendency Packages
      tags: dependencies
      become: true
      package: name={{ item }} state=latest
      with_items:
        - tmux
        - monit

  roles:
    - { role: bitcoin, when:  currency_type == 'bitcoin' }
    - { role: litecoin, when:  currency_type == 'litecoin' }
    - { role: ethereum, when:  currency_type == 'ethereum' }

  tasks:
    - name: Monit Config
      tags: monit_config
      become: true
      shell: |
        echo "empty for now"
      #perhpas this should become a role...      
#TODO: probably can't just run daemon, we need to restart.
#TODO: might make sense to add to cron here and reboot?
#TODO: add monit 




















