- name: Setup monitrc file
  tags: setup_monitrc
  become: true
  blockinfile:
    dest: /etc/monit/monitrc
    create: yes
    owner: root
    group: root
    mode: 0600
    block: |
      {{ monitrc_file_content }}
