- name: Setup monitrc file base
  tags: setup_monitrc_base
  become: true
  blockinfile:
    dest: "{{ monit_control_path }}"
    create: yes
    owner: root
    group: root
    mode: 0600
    block: |
      {{ monitrc_file_content }}
