- name: Clear monitrc file
  tags: clear_monitrc_contents
  become: true
  file:
    state: absent
    path: "{{ monit_control_path }}"

- name: Setup monitrc file base
  tags: setup_monitrc_base
  become: true
  blockinfile:
    dest: "{{ monit_control_path }}"
    create: yes
    owner: root
    group: root
    mode: 0600
    block: |
      {{ monitrc_file_content }}

- name: Setup monitrc SMTP
  tags: setup_monit_smtp
  become: true
  blockinfile:
    dest: "{{ monit_control_path }}"
    insertafter: EOF
    block: |
      {{ monit_mail_server }}
  when: setup_smtp
