alert_email: <TODO>

monitrc_file_content: |
  set daemon 60
  set logfile /var/log/monit.log
  set alert {{ alert_email }} only on { nonexist }

  set mail-format {
    subject: $SERVICE $DESCRIPTION on $HOST
    message: $DATE
             $SERVICE $DESCRIPTION on $HOST
             $SERVICE $ACTION             
  }
