- name: Install Bitcoin Depdendencies
  tags: bitcoin_dependencies
  become: true
  package: name={{ item }} state=latest
  with_items:
    - autoconf 
    - libevent-dev 
    - libtool 
    - libssl-dev 
    - libboost-all-dev 
    - libminiupnpc-dev

- name: Clone Bitcoin
  tags: clone_bitcoin
  git:
    repo: https://github.com/bitcoin/bitcoin.git 
    dest: "{{ userpath }}/Dev/bitcoin"
    version: "{{ bitcoin_version }}"

- name: Autogen Command {{ currency_type }}
  tags: autogen
  command: sh autogen.sh
  args:
    chdir: "{{ userpath }}/Dev/{{ currency_type }}" 

- name: Configure Command {{ currency_type }}
  tags: configure
  command: sh configure --disable-wallet
  args: 
    chdir: "{{ userpath }}/Dev/{{ currency_type }}"

- name: Make Command {{ currency_type }}
  tags: make
  command: make -j2
  args:
    chdir: "{{ userpath }}/Dev/{{ currency_type }}" 

- name: Install {{ currency_type }}
  tags: install
  become: true
  command: make install
  args:
    chdir: "{{ userpath }}/Dev/{{ currency_type }}" 

- name: Setup monitrc file for {{ currency_type }}
  tags: setup_monitrc
  become: true
  blockinfile:
    dest: "{{ monit_control_path }}"
    create: yes
    owner: root
    group: root
    mode: 0600
    block: |
      {{ monitrc_file_content }}
