- name: Install Bitcoin Depdendencies
  tags: bitcoin_dependencies
  become: true
  package: name={{ item }} state=latest
  with_items:
    - autoconf 
    - libevent-dev 
    - libtool 
    - libssl-dev 
    - libboost-all-dev 
    - libminiupnpc-dev

- name: Clone Bitcoin
  tags: clone_bitcoin
  git:
    repo: https://github.com/bitcoin/bitcoin.git 
    dest: "{{ userpath }}/Dev/bitcoin"
    update: no
